version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  # Comment this if don't want to save log file
  # file:
  #   class: logging.FileHandler
  #   formatter: simple
  #   filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
root:
  level: INFO # Logging Levels
  handlers:
  - console
  # - file # Comment this if don't want to save to log file
disable_existing_loggers: false