# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training

# Train settings -------------------------------------------------------------------------------------------------------
data: ./new_data/data.yaml # (str, optional) path to data file, i.e. coco8.yaml
epochs: 100 # (int) number of epochs to train for
batch: 16 # (int) number of images per batch (-1 for AutoBatch)
device: # (int | str | list, optional) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
project: fire_detection_yolo # (str, optional) project name
optimizer: auto # (str) optimizer to use, choices=[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True # (bool) whether to print verbose output
amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check

# Hyperparameters ------------------------------------------------------------------------------------------------------
box: 7.5 # (float) box loss gain
cls: 0.5 # (float) cls loss gain (scale with pixels)
dfl: 1.5 # (float) dfl loss gain